export const FETCH_INCIDENTS = 'FETCH_INCIDENTS';
export const SORT_INCIDENTS = 'SORT_INCIDENTS';

export const FETCH_INCIDENT = 'FETCH_INCIDENT';


export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';